config/routes.rb
Tabup::Application.routes.draw do
  resources :things

  root 'things#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thing }
      else
        format.html { render action: 'new' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <!--<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
    <!--<div class="container">-->
      <!--<div class="navbar-header">-->
        <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
          <!--<span class="sr-only">Toggle navigation</span>-->
          <!--<span class="icon-bar"></span>-->
          <!--<span class="icon-bar"></span>-->
          <!--<span class="icon-bar"></span>-->
        <!--</button>-->
        <!--<a class="navbar-brand" href="#">Project name</a>-->
      <!--</div>-->
      <!--<div class="collapse navbar-collapse">-->
        <!--<ul class="nav navbar-nav">-->
          <!--<li class="active"><a href="#">Home</a></li>-->
          <!--<li><a href="#about">About</a></li>-->
          <!--<li><a href="#contact">Contact</a></li>-->
        <!--</ul>-->
      <!--</div>&lt;!&ndash;/.nav-collapse &ndash;&gt;-->
    <!--</div>-->
  <!--</div>-->

  <div class="container">

    <div class="starter-template">
      <h1>Bootstrap starter template</h1>
      <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>

      <%= yield %>
      <%= javascript_include_tag "application" %>


    </div>

  </div><!-- /.container -->


  </body>
</html>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<table id="sortable" class="table table-striped table-bordered table-hover table-condensed table-responsive  draggable sortable">
  <tbody>
  <tr>
    <th>Name</th>
    <th>What is it</th>
    <th>When is it</th>
    <th>Tags</th>
    <th>Other</th>
  </tr>
  <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td>other stuff</td>
        <td><%= thing.saved_date.strftime(" %_m/%e")  %></td>
        <td></td>
        <td></td>
      </tr>
  <% end %>


  </tbody>
</table>

<table class="responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Detail 1</th>
      <th>Detail 2</th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %> lkjsdhlaskjdfhaslkjdfhaslkdjfhaslkdjfhaslkjdhflaskjdhflaskjdhf</td>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>



</script>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>